#!/usr/bin/env node
/*
 * generate-docs.js — Runway docs generator
 * =========================================
 * PHASE 0 SKELETON. Proves the generator architecture without requiring all skills to exist.
 *
 * What it does today (skeleton scope, per PHASE_00 acceptance criteria):
 *   - Discovers skills/<name>/SKILL.md files (if any exist yet).
 *   - Parses the YAML front-matter (top-level scalar fields only — see parseFrontmatterScalars).
 *   - Emits one stub reference page: site/docs/agents.md, listing name / slash_command / model /
 *     description for each skill. If no skills exist yet, writes a clearly-marked placeholder.
 *
 * Roadmap:
 *   - PHASE_12a: extend to render a full reference page for one skill (init), proving the pipeline E2E.
 *   - PHASE_12b: read ALL 8 SKILL.md files + all 7 schemas; generate agents.md, commands.md,
 *     schemas.md with full tables and schema cross-references. Swap parseFrontmatterScalars() for a
 *     real YAML parser (js-yaml) to handle nested inputs/outputs/errors/examples.
 *
 * Design rules:
 *   - Zero runtime dependencies (CI runs `node scripts/generate-docs.js` with no install step).
 *   - Deterministic output (skills sorted by name) so the CI "docs rebuild check" can diff against
 *     the committed site/docs/ and fail if a SKILL.md changed without a docs rebuild.
 *   - Generated files carry a "DO NOT EDIT DIRECTLY" banner.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SKILLS_DIR = path.join(ROOT, 'skills');
const SCHEMAS_DIR = path.join(ROOT, 'schemas');
const OUT_DIR = path.join(ROOT, 'site', 'docs');

const GENERATED_BANNER =
  '<!-- DO NOT EDIT DIRECTLY. Generated by scripts/generate-docs.js. Run `node scripts/generate-docs.js`. -->';

/**
 * Split a markdown-with-frontmatter file into { frontmatter, body }.
 * Returns { frontmatter: '', body: raw } when no leading `---` fence is present.
 */
function splitFrontmatter(raw) {
  const text = raw.replace(/^﻿/, '');
  if (!text.startsWith('---')) return { frontmatter: '', body: text };
  const end = text.indexOf('\n---', 3);
  if (end === -1) return { frontmatter: '', body: text };
  const fmStart = text.indexOf('\n') + 1;
  const frontmatter = text.slice(fmStart, end + 1);
  const body = text.slice(text.indexOf('\n', end + 1) + 1);
  return { frontmatter, body };
}

/**
 * Minimal top-level-scalar YAML parser — SKELETON ONLY.
 * Captures lines of the form `key: value` at column 0 where value is a non-empty scalar.
 * Intentionally ignores nested lists/objects (inputs, outputs, errors, examples); PHASE_12b
 * replaces this with a real YAML parser.
 */
function parseFrontmatterScalars(frontmatter) {
  const out = {};
  for (const line of frontmatter.split('\n')) {
    if (!line || /^\s/.test(line)) continue; // skip nested / indented lines
    const m = line.match(/^([A-Za-z0-9_]+):[ \t]*(.*)$/);
    if (!m) continue;
    let [, key, value] = m;
    value = value.trim();
    if (value === '' || value === '|' || value === '>') continue; // block scalar / container — skip in skeleton
    value = value.replace(/^["'](.*)["']$/, '$1'); // strip surrounding quotes
    out[key] = value;
  }
  return out;
}

/** Discover skills/<name>/SKILL.md, sorted by directory name for deterministic output. */
function discoverSkills() {
  if (!fs.existsSync(SKILLS_DIR)) return [];
  return fs
    .readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()
    .map((name) => ({ name, file: path.join(SKILLS_DIR, name, 'SKILL.md') }))
    .filter((s) => fs.existsSync(s.file))
    .map((s) => {
      const { frontmatter } = splitFrontmatter(fs.readFileSync(s.file, 'utf8'));
      return { dir: s.name, fields: parseFrontmatterScalars(frontmatter) };
    });
}

function renderAgentsStub(skills) {
  const lines = [GENERATED_BANNER, '', '# Agent Reference', ''];
  if (skills.length === 0) {
    lines.push(
      '_No skills found under `skills/` yet. This page will be populated once skills are scaffolded',
      '(PHASE_01) and the generator is extended (PHASE_12a/PHASE_12b)._',
      ''
    );
    return lines.join('\n');
  }
  lines.push('| Skill | Command | Model | Description |', '|---|---|---|---|');
  for (const s of skills) {
    const f = s.fields;
    lines.push(
      `| ${f.name || s.dir} | \`${f.slash_command || '—'}\` | ${f.model || '—'} | ${f.description || '—'} |`
    );
  }
  lines.push('');
  return lines.join('\n');
}

function main() {
  const skills = discoverSkills();
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const outFile = path.join(OUT_DIR, 'agents.md');
  fs.writeFileSync(outFile, renderAgentsStub(skills), 'utf8');

  const rel = path.relative(ROOT, outFile);
  console.log(
    `generate-docs: ${skills.length} skill(s) discovered → wrote ${rel}` +
      (skills.length === 0 ? ' (placeholder)' : '')
  );
  // Note: SCHEMAS_DIR is wired up for PHASE_12b (schema reference) but not read in the skeleton.
  void SCHEMAS_DIR;
}

if (require.main === module) {
  try {
    main();
  } catch (err) {
    console.error('generate-docs: FAILED —', err.message);
    process.exit(1);
  }
}

module.exports = { splitFrontmatter, parseFrontmatterScalars, discoverSkills, renderAgentsStub };
